export const ActionImg = {
  GE_LOAD: "GE_LOAD",
  GET_IMG: "GET_IMG",
  GET_IMG_ERROR: "GET_IMG_ERROR",
  // ALL
  GET_ALL_IMG_LOAD: "GET_ALL_IMG_LOAD",
  GET_ALL_IMG: "GET_ALL_IMG",
  GET_ALL_IMG_ERROR: "GET_ALL_IMG_ERROR",
  /// ADD
  ADD_LOAD: "ADD_LOAD",
  ADD_IMG: "ADD_IMG",
  ADD_IMG_ERROR: "ADD_IMG_ERROR",
  // DELETE
  DELETE_IMG_LOAD: "DELETE_IMG_LOAD",
  DELETE_IMG: "DELETE_IMG",
  DELETE_IMG_ERROR: "DELETE_IMG_ERROR",
  // UPDATE_IMG
  UPDATE_IMG_LOAD: "UPDATE_IMG_LOAD",
  UPDATE_IMG: "UPDATE_IMG",
  UPDATE_IMG__ERROR: "UPDATE_IMG__ERROR",
  // likes
  LIKE_IMG_LOAD: "LIKE_IMG_LOAD",
  LIKE_IMG: "LIKE_IMG",
  LIKE_IMG_ERROR: "LIKE_IMG_ERROR",
  // comments
  COMMENT_IMG_LOAD: "COMMENT_IMG_LOAD",
  COMMENT_IMG: "COMMENT_IMG",
  COMMENT_IMG_ERROR: "COMMENT_IMG_ERROR",
  // GET COMMENTS
  GET_COMMENTS_LOAD: "GET_COMMENTS_LOAD",
  GET_COMMENTS: "GET_COMMENTS",
  GET_COMMENTS_ERROR: "GET_COMMENTS_ERROR"

};
