export const ActionImg = {
    GET_IMG: "GET_IMG",
    ADD_IMG: "ADD_IMG",
    ADD_IMG_ERROR: "ADD_IMG_ERROR",
    DELETE_IMG: "DELETE_IMG",
    UPDATE_IMG: "UPDATE_IMG",
    UPDATE_IMG__ERROR: "UPDATE_IMG__ERROR"
}
