export const ActionNotes = {
  // GET NOTES
  GET_NOTES: "GET_NOTES",
  GET_NOTES_LOAD: "GET_NOTES_LOAD",
  GET_NOTES_SUCCESS: "GET_NOTES_SUCCESS",
  GET_NOTES_ERROR: "GET_NOTES_ERROR",
  // ADD NOTES
  ADD_NOTES: "ADD_NOTES",
  ADD_NOTES_LOAD: "ADD_NOTES_LOAD",
  ADD_NOTES_SUCCESS: "ADD_NOTES_SUCCESS",
  ADD_NOTES_ERROR: "ADD_NOTES_ERROR",
  // EDITE NOTES
  EDITE_NOTES: "EDITE_NOTES",
  EDITE_NOTES_LOAD: "EDITE_NOTES_LOAD",
  EDITE_SUCCESS: "EDITE_SUCCESS",
  EDITE_NOTES_ERROR: "EDITE_NOTES_ERROR",
  // DELELTE NOTES
  DELETE_NOTES: "DELETE_NOTES",
  DELETE_NOTES_LOAD: "DELETE_NOTES_LOAD",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_NOTES_ERROR: "DELETE_NOTES_ERROR"

};
