
export enum PostActionType {
    LOAD_ALL_POST = "LOAD_ALL_POST",
    LOAD_ALL_POST_SUCCESS = "LOAD_ALL_POST_SUCCESS",
    LOAD_ALL_POST_ERROR = "LOAD_ALL_POST_ERROR",
    LOAD_POST_USER = "LOAD_POST_USER",
    LOAD_POST_USER_SUCCESS = "LOAD_POST_USER_SUCCESS",
    LOAD_POST_USER_ERROR = "LOAD_POST_USER_ERROR",
    LOAD_UPLOAD_POST = "LOAD_UPLOAD_POST",
    LOAD_UPLOAD_POST_SUCCESS = "LOAD_UPLOAD_POST_SUCCESS",
    LOAD_UPLOAD_POST_ERROR = "LOAD_UPLOAD_POST_ERROR",
    LOAD_DELETE_POST = "LOAD_DELETE_POST",
    LOAD_DELETE_POST_SUCCESS = "LOAD_DELETE_POST_SUCCESS",
    LOAD_COMMENTS_POST = "LOAD_COMMENTS_POST",
    LOAD_COMMENTS_POST_SUCCESS = "LOAD_COMMENTS_POST_SUCCESS",
    LOAD_COMMENTS_POST_ERROR = "LOAD_COMMENTS_POST_ERROR",
}


